
- paru:
  - swayfx
  - xorg-xwayland
  - swaybg
  - swayidle
  - swaync
  - libnotify # For notify-send
  - waybar
  - wlr-randr
  - wlogout
  - rofi
  # - ttf-nerd-fonts-symbols   
  - ttf-font-awesome
  # - papirus-icon-theme


